version: 2.1

orbs:
  python: circleci/python@3.2.0

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          name: Run tests
          command: |
            uv run pytest --cov=./ --cov-report=xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage.xml

workflows:
  test-workflow:
    jobs:
      - test
